[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[6001]
type=endpoint
context=voice-captcha
disallow=all
allow=ulaw
allow=alaw
allow=g722
auth=auth6001
aors=aor6001
rtp_symmetric=yes
force_rport=yes
ice_support=yes

[auth6001]
type=auth
auth_type=userpass
password=1234
username=6001

[aor6001]
type=aor
max_contacts=1

